# Generated by Django 5.1.6 on 2025-02-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0002_book_price_alter_book_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
